### ISSUE TITLE
Zeitgeist Configuration

### ISSUE THREAD

**Issue by sgerodes** [FrankBevr/Things#7]
There are several parameters that we can tweeks for the market creation logic:
- duration of the market. Right now it defaults to 14 days
- do we need a swap fee? Right now it is 1%. Everybody who votes on the market will pay this amount to the creator.
- tags. You can see tags on top of the market. Current tags list:["Governance", "Crypto", "Kusama", "Polkasembly", "Futurarchy"]
- question. My proposal is to make it just static to smth like "Will the polkasembly proposal <proposalNumber> resolve?"
- description. Smth like "This market was created automatically and is bonded to the polkasembly bounty <link_to_bounty>"
- slug. "polkasembly-bounty-<nr_of_polkasembly_bounty>"

**Comment by morkeltry** [comment]
Duration of the market is the most important question 
 (if a market resolves too early, then it changes the incentive model so that there is money to be made on predicting things other than pass/ fail - this screws up some important use cases, for example, people may arbitrage for small gain - small gain is not worth it if there is uncertainty rather than just known risk involved)
 I don't see a disadvantage to users in a market resolving too late - unless it is much too late (like six months) - then they lose the opportunity value of the capital tied up in the market.

It looks like proposals which are not fast tracked have 28 days to be accepted. However, I'm not sure how this is cleaned up after the 28 days - the chain may wait, eg, until the end of the epoch or era.
(and better, if possible, to count time from the `Treasury.Proposal` event that triggers it, not from the time the market is created - since our bot may sleep and batch process events some time after they are emitted.
** Therefore, I would suggest a resolution time of 28 days, 6 hours and 1 block after the `Treasury.Proposal` event is included in a block = block  `event.blockNumber + 28.25*3600+1` **

Swap fee is configurable per market, ie we can add it later.
Given the need to attract liquidity and hopefully arbitrageurs, I'd say keep swap fee at zero if it doesn't mess with the economics of a market.

Tags sound great idea but we need to think about the UI - how to represent these in polkassembly post?

Description - we will have a couple of paragraphs in which to write so we can afford to spend some words before we lose interest - let's add something fun :)

Question - This is a formal description, we need to be exact and concise with words, eg:
'Will Treasury Proposal X on Kusama be Accepted or Rejected by on-chain event before X time: Accepted/Rejected/Neither'
(I can't imagine what neither is atm, but possible they may, eg, introduce a proposal format which breaks our model)

slug - suggest: KSM-treasury-prop-X

**Comment by FrankBevr** [comment]
I closed that issue.
I guess that issue was already handled in the main repo. 

Sidenote:
This Repo was changed to [Quickstart of Futurachy](https://github.com/PolkaHack/futarchy)
Further issues please write further issues [here](https://github.com/PolkaHack/futarchy/issues).
